openapi: "3.0.3"
info:
  title: Wazuh Indexer Command Manager API
  version: "1.0"
servers:
  - url: http://127.0.0.1:9200/_plugins/_command_manager
paths:
  /commands:
    post:
      tags:
        - "commands"
      summary: Add commands.
      description: Receives and processes an array of commands.
      requestBody:
        required: true
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/Commands"
            examples:
              restart:
                summary: Restart command
                value:
                  commands:
                    - action:
                        args: {}
                        name: restart
                        version: "5.0.0"
                      source: "Users/Services"
                      user: "Management API"
                      timeout: 100
                      target:
                        id: "d5b250c4-dfa1-4d94-827f-9f99210dbe6c"
                        type: "agent"
              fetch-config:
                summary: Fetch configuration command
                value:
                  commands:
                    - action:
                        args: {}
                        name: fetch-config
                        version: "5.0.0"
                      source: "Users/Services"
                      user: "Management API"
                      timeout: 100
                      target:
                        id: "d5b250c4-dfa1-4d94-827f-9f99210dbe6c"
                        type: "agent"
              set-group:
                summary: Set group command
                value:
                  commands:
                    - action:
                        args:
                          groups:
                            - "group_1"
                            - "group_2"
                        name: set-group
                        version: "5.0.0"
                      source: "Users/Services"
                      user: "Management API"
                      timeout: 100
                      target:
                        id: "d5b250c4-dfa1-4d94-827f-9f99210dbe6c"
                        type: "agent"
      responses:
        "200":
          description: OK
        "400":
          description: parsing_exception
        "500":
          description: Internal server error (boom!)

components:
  schemas:
    Commands:
      type: object
      properties:
        commands:
          type: array
          items:
            $ref: '#/components/schemas/Command'
    Command:
      type: object
      properties:
        source:
          type: string
          example: "Users/Services"
        user:
          type: string
          example: "Management API"
        target:
          $ref: '#/components/schemas/Target'
        action:
          $ref: '#/components/schemas/Action'
        timeout:
          type: integer
          example: 100
    Target:
      type: object
      properties:
        id:
          type: string
          example: "d5b250c4-dfa1-4d94-827f-9f99210dbe6c"
        type:
          type: string
          example: "agent"
    Action:
      type: object
      properties:
        name:
          type: string
          enum: [restart, fetch-config, set-group]
          example: "set-group"
        args:
          type: object
          properties:
            groups:
              type: array
              items:
                type: string
              example: 
                - "group_1"
                - "group_2"
        version:
          type: string
          example: "5.0.0"
